export default {
  addFiles: "add-files",
  archive: "archive",
  backward: "backward",
  bold: "bold",
  bookmark: "bookmark",
  calculator: "calculator",
  calendar: "calendar",
  checkmark: "checkmark",
  chevronLeft: "chevron-left",
  clipboard: "clipboard",
  close: "close",
  code: "code",
  coffeeCup: "coffee-cup",
  cog: "cog",
  creativeCommons: "creative-commons",
  cut: "cut",
  download: "download",
};
