export default {
	addFiles: "add-files",
	archive: "archive",
	arrowLeft: "arrow-left",
	arrowRight: "arrow-right",
	backward: "backward",
	bold: "bold",
	bookmark: "bookmark",
	calculator: "calculator",
	calendar: "calendar",
	checkmark: "checkmark",
	chevronLeft: "chevron-left",
	chevronRight: "chevron-right",
	clipboard: "clipboard",
	close: "close",
	code: "code",
	coffeeCup: "coffee-cup",
	cog: "cog",
	creativeCommons: "creative-commons",
	cut: "cut",
	download: "download",
	eraser: "eraser",
	eye: "eye",
	folder: "folder",
	questionCircle: "question-circle",
};
